### ISSUE TITLE
can not compile with cudnn=1 cuda-11.2 cudnn8.1.1

### ISSUE THREAD

**Issue by daliel** [opendatacam/opendatacam#445]
faced the same problem.
downloaded the darknet from https://github.com/AlexeyAB/darknet/
changed:

```
GPU = 1
CUDNN = 1
OPENCV = 1
CUDNN_HALF = 1
arch=compute_86,code=[sm_86, compute_86]
else
LDFLAGS + = -L/usr/local/cuda-11.2/lib64 -lcuda -lcudart -lcublas -lcurand
endif
else
CFLAGS + = -DCUDNN -I/usr/local/cuda-11.2/include
LDFLAGS + = -L/usr/local/cuda-11.2/lib64 -lcudnn
endif
```
run make

everything works.
then:
downloaded the darknet from https://github.com/opendatacam/darknet
made the same changes as above.
after the make received an error:

```
[./src/convolutional_layer.c:286:24: error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3’?
     int forward_algo = CUDNN_CONVOLUTION_FWD_PREFER_FASTEST;
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3
compilation terminated due to -Wfatal-errors.
Makefile: 163: recipe for target 'obj / convolutional_layer.o' failed
make: *** [obj / convolutional_layer.o] Error 1]
```
what changes did you make? Will the odc work if I replace your darknet with AlexeyAB / darknet?
after merging the two distributions, the container started up.
I'm not sure about the structure of the json that the darknet returns.
in the spam console:
```
opendatacam_1 | JSON-stream sent.
opendatacam_1 |
opendatacam_1 | FPS: 14.7 AVG_FPS: 12.4
opendatacam_1 | known client: 26, sent = 235819, must be sent outlen = 235819
opendatacam_1 | known client: 26, sent = 237783, must be sent outlen = 237783
opendatacam_1 | MJPEG-stream sent.
opendatacam_1 | Objects:
opendatacam_1 |
opendatacam_1 | JSON-stream sent.
opendatacam_1 |
opendatacam_1 | FPS: 14.8 AVG_FPS: 12.4
opendatacam_1 | known client: 26, sent = 236547, must be sent outlen = 236547
opendatacam_1 | MJPEG-stream sent.
opendatacam_1 | Objects:
opendatacam_1 |
opendatacam_1 | JSON-stream sent.
opendatacam_1 |
opendatacam_1 | FPS: 14.4 AVG_FPS: 12.4
opendatacam_1 | known client: 26, sent = 236613, must be sent outlen = 236613
opendatacam_1 | MJPEG-stream sent.
opendatacam_1 | Objects:
```

because of spam, the log grows very quickly.
